### PR TITLE
Added support for MetaEvent Time Signature see #7

### PR DESCRIPTION
**Pull request by lplume**
first of all sorry about the empty spaces deletion, apparently my editor did it ^^'
This should add support to the Time Signature Meta Event, I added it as a Track method (just like the set tempo).

Please note that in MIDI 1 file format every time related meta event should be defined in the first track.

<s>I used default parameter in the function signature</s> (I am not really comfortable with javascript).

### CODE REVIEW

**Comment by shivrajsa** [comment]
Could you please add usage example, it will be very helpful.

**Comment by lplume** [comment]
Here you go =)
```
var track = new MidiWriter.Track();
tracks.setTimeSignature(3, 4);

```

setTimeSignature(numerator, denominator)

**Comment by grimmdude** [comment]
Hi @lplume,

Looks great, I will try this out later today and merge.  Thanks for the help,

-Garrett

**Comment by grimmdude** [comment]
Looks good, thanks again.  This has been merged,

-Garrett

**Pull request merged**
