### PR TITLE
Add browser support to save .mid file in browser.

### PR DESCRIPTION
**Pull request by yilihjy**
Hello, I have did a little work to support this lib to run in browser. 
This change only add a browser.js file in build folder.
When somebody want to use this lib to create a .mid file in browser, use this new file.
For example, I use this lib in a vue project like below:
```javascript
import MidiWriter from 'midi-writer-js'
\\ ......
var track = new MidiWriter.Track();
var note = new MidiWriter.NoteEvent({pitch: ['C4', 'D4', 'E4'], duration: '4'});
track.addEvent(note);
var write = new MidiWriter.Writer(track);
write.saveMIDI('test');
\\ ......
```
These code run well!

### CODE REVIEW

**Comment by grimmdude** [comment]
Hi @yilihjy,

Thanks for taking a swing at it.  I think we can do this without the extra dependencies and just minor config changes to rollup.config.js.  You can see how we handled in MidiPlayerJS:

https://github.com/grimmdude/MidiPlayerJS/blob/0c9c74f8b7eb6daaeca1420c211e045a770cbffb/rollup.config.js#L5-L15

**Comment by grimmdude** [comment]
Fixes https://github.com/grimmdude/MidiWriterJS/issues/70

**Comment by yilihjy** [comment]
Hi @grimmdude , I have trid your former advice. But when I had reomved the dependence of `@rollup/plugin-replace` , some bad things happened.
In my vue nuxt project (a webpack project), some error occured , like below:
```
 ERROR  Failed to compile with 1 errors                                                                                       friendly-errors 11:01:43  

This dependency was not found:                                                                                                friendly-errors 11:01:43  
                                                                                                                              friendly-errors 11:01:43  
* fs in ./node_modules/midi-writer-js/browser/midiwriter.js                                                                   friendly-errors 11:01:43  
                                                                                                                              friendly-errors 11:01:43  
To install it, you can run: npm install --save fs                                                                             friendly-errors 11:01:43 
```
To deal with it, I created a rollup.config.browser.js for browser build.
Now, there are three new files in brower folder.
`brower/index.mjs`
It is a esm file for webpack project. Just use `import MidiWriter from 'midi-writer-js'` to use in webpack project.  
`midiwriter.bundle.js` and `midiwriter.bundle.min.js` 
for <script> tag in browser. A little demo in example/DownloadFileInBrowser.html

**Comment by brineryte** [comment]
Any update on this? I had this working using quokka jsut to play around with it, but I am trying to create a basic html page to enter some input and use that to generate the midi. Maybe I'm just a n00b but I can't figure out how to properly include midi-writer-js in my js file.

I re-ran `npm install` recently. I'm using the recommended require('midi-writer-js), for which I had to include require.js into my project. I am currently getting an error: Uncaught Error: Module name "midi-writer-js" has not been loaded yet for context: _. Use require([])

Any insight is appreciated!

my repo: https://github.com/brineryte/randomidi

**Comment by yilihjy** [comment]
@brineryte  
There is my example code [https://github.com/yilihjy/MidiWriterJS/blob/browserify/examples/DownloadFileInBrowser.html](https://github.com/yilihjy/MidiWriterJS/blob/browserify/examples/DownloadFileInBrowser.html).
This html page will download a .midi file from browser when you click the button.
Could it help you?

**Comment by brineryte** [comment]
@yilihjy Thank you, I'll check that out!

**Comment by mitchkm** [comment]
It would also be nice to have this package rollup for the browser. As the `saveMIDI` function is the only one that causes an issue in the browser, can it just be removed? Anyone who wants to save the file can do so themselves, same as anyone wanting to download the midi in-browser.

**Comment by grimmdude** [comment]
I've removed the `Writer.saveMIDI()` in version 2.0.0 which removes the dependency on the Node specific `fs` module.  This should fix issues when building this library for browser usage.

MIDI data can be returned by using another one of the existing methods on the [`Writer`](https://grimmdude.com/MidiWriterJS/docs/Writer.html) class.  Gonna close this out for now.

**Pull request closed without merging**
